language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="d5c9550f-1c3e-4972-8b36-72113abbca74"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -rail.shamsemukhametov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always